### ISSUE TITLE
fix lighthouse statistic and apply best-practices

### ISSUE THREAD

**Issue by felixhaeberle** [hfg-gmuend/openmoji-website#45]
Today I checked the current website with the famous Google Lighthouse test and got some pretty bad stats, there is room for improvement.

Tested with throttling enabled. On Desktop.
<img width="778" alt="Screenshot 2019-09-21 13 51 37" src="https://user-images.githubusercontent.com/34959078/65373431-dbe8ca80-dc7d-11e9-90fc-c2f0abaec22a.png">
Tested with throttling disabled. On Desktop.
<img width="777" alt="Screenshot 2019-09-21 13 50 41" src="https://user-images.githubusercontent.com/34959078/65373432-dbe8ca80-dc7d-11e9-870f-f499a7e32346.png">

To test this by yourself, open the Chrome DevTools and go to "Audits", after, run the test of your choice. The test result provides some guidance on how to solve these problems.

**Comment by b-g** [comment]
Hi @felixhaeberle Many thanks for "den Finger in die Wunde zu legen"! :) Yes you are right. Could be a lot better. To our excuse I just can say that this was all done with students and volunteers ... and we already had a hard time to design and figure out the emojis part ... in the end there was never enough time to really professionally implement the website. Sorry!

Interestingly the lighthouse test perform slightly different on my end. I always get 100% performance! (But this might be due to the fact that I connected to a quite speedy internet connection at CMU here in Pittsburgh ... still odd).

Would you be willing to improve the lighthouse audits? 

<img width="1785" alt="Screen Shot 2019-09-23 at 17 17 14" src="https://user-images.githubusercontent.com/480224/65464120-2194c700-de27-11e9-8e06-f54bf3839490.png">
<img width="1785" alt="Screen Shot 2019-09-23 at 17 20 18" src="https://user-images.githubusercontent.com/480224/65464121-2194c700-de27-11e9-8c81-925df671cb8d.png">

**Comment by felixhaeberle** [comment]
Yes, performance should be influenced by your connection and your CPU, which can be slowed down to an average level by DevTools in the settings. 🎛

Ha, please don't apologize, I have worked on big corporate sites in the past where lighthouse results were even worse. 🚑

Sure, at least the accessibility issue is a hard pain point for me. After, I take care about the other points. Should take some days until I can get into it but yes, it's on my list 👨🏻‍💻

**Comment by b-g** [comment]
Great! 👍

**Comment by felixhaeberle** [comment]
Managed to get pretty good results on the front page, applying them now to the other pages aswell. 💯 

<img width="1437" alt="Screenshot 2019-10-22 02 25 59" src="https://user-images.githubusercontent.com/34959078/67252481-69812b00-f473-11e9-92d3-491b14afa7c1.png">

**Comment by b-g** [comment]
@felixhaeberle YAY! 💯! 🙏!

**Comment by b-g** [comment]
@felixhaeberle Should we close this issue as of https://github.com/hfg-gmuend/openmoji-website/pull/50 ?

**Comment by felixhaeberle** [comment]
@b-g yes, thank you! 👍
