### ISSUE TITLE
Make subpages responsive (improve mobile)

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#47]

**Comment by felixhaeberle** [comment]
Figma link to the updated design
https://www.figma.com/file/IPDkZy9bolQiXRGGnzIVHDDD/openmoji_website_v2

**Comment by carlinmack** [comment]
Do we have any timeline on when v2 should be implemented by? I could do more proofreading of the current website but it's futile if all the copy will change with v2

**Comment by b-g** [comment]
@carlinmack Happy to have you do proofreading. The OpenMoji website won't change a lot in terms of text. @felixhaeberle is "just" working on improving it in terms of mobile support and SEO. Please go ahead if you have time and energy.

**Comment by felixhaeberle** [comment]
Made good progress in the last days, will submit my first proposal tomorrow for first feedback. 🌟

**Comment by b-g** [comment]
@felixhaeberle Looking forward!!

**Comment by b-g** [comment]
@felixhaeberle 
Review PR #63 
Yay! Great improvements! Comments:

**General**
- [ ] Sticky header is nice, but would align OpenMoji more left and the hamburger menu icon more right
![2019-12-17 at 10 51](https://user-images.githubusercontent.com/480224/71011495-7a3cce80-20bb-11ea-8014-7f8dce331cd6.jpg)

- [ ] It would be nicer to have Imprint and License in a single line in Footer. Maybe simply get rid of "License" (also on desktop) and leave one Imprint and CC BY-SA 4.0.
![2019-12-17 at 10 54](https://user-images.githubusercontent.com/480224/71011539-95a7d980-20bb-11ea-90f9-93954addc78d.jpg)

- [ ] Imprint can't be closed. Please add "X" like in main menu

- [ ] Wondering whether it would not be better to have for the subpages the title in the header instead of the big OpenMoji text ... ?

**library**
- [ ] I think it would be nicer to have everything in a single line: "Groups {icon} Color {icon} Sorting {icon}". I think it might be better to use "everything" instead of "all OpenMojis".
![2019-12-17 at 11 00](https://user-images.githubusercontent.com/480224/71012178-ab69ce80-20bc-11ea-9e97-f204988f9a4f.jpg)

- [ ] Groups selector can't be closed. Please add "X" like in main menu

- [ ] Detail: bring "X" up in top right corner, make left/right buttons bigger, less padding between skintones and emoji, more padding for title, would have svg and png button simply at the buttom of the page.
![2019-12-17 at 11 09](https://user-images.githubusercontent.com/480224/71013237-5b8c0700-20be-11ea-90bf-a69026b0deae.jpg)

**styleguide**
Nice! No comments! :)

**samples**
- [ ] please reduce a bit the padding between images
![2019-12-17 at 11 16](https://user-images.githubusercontent.com/480224/71013429-ac036480-20be-11ea-975c-6d4c47107108.jpg)

**about**
Nice! No comments! :)

**Comment by felixhaeberle** [comment]
Thanks for your review @b-g ! Great comments and the sorting of the emojis now makes much more sense with your suggestions. Let's get this ready until 🎄🌟 I'll proceed on this on the weekend 🤓

**Comment by b-g** [comment]
@felixhaeberle Great! Much looking forward! Also let's aim to be pragmatic ... the mobile state on Dec 23 should at least be release-able but doesn't have to be perfect. Most important is to get everything out!

**Comment by felixhaeberle** [comment]
I'm going to apply your feedback today 👍

**Comment by felixhaeberle** [comment]
see #63 🔢

**Comment by felixhaeberle** [comment]
Here comes the full feedback to the change request:

1.  > Sticky header is nice, but would align OpenMoji more left and the hamburger menu icon more right

Done! ✅ 

2.  > Imprint can't be closed. Please add "X" like in main menu

Done!  ✅ 

3. > Wondering whether it would not be better to have for the subpages the title in the header instead of the big OpenMoji text ... ?

Not sure. Do you want to stripe out the normal headings of the pages then and display the pages name in the heading then?

4. >  I think it would be nicer to have everything in a single line: "Groups {icon} Color {icon} Sorting {icon}". I think it might be better to use "everything" instead of "all OpenMojis".

Done! ✅ 

5. > Groups selector can't be closed. Please add "X" like in main menu

Done! ✅ 

6. > Detail: bring "X" up in top right corner, make left/right buttons bigger, less padding between skintones and emoji, more padding for title, would have svg and png button simply at the buttom of the page.

Done, but left the right/left buttons in place, I didn't understand your change request. Maybe it's good already? Screenshots for comparison of how this aligns in the different cases: 
<div style="display:flex">
<img width="49%" src="https://user-images.githubusercontent.com/34959078/71590155-b0e8ff00-2b27-11ea-80cc-7a5a88118093.png"/>
<img width="49%" src="https://user-images.githubusercontent.com/34959078/71590167-be05ee00-2b27-11ea-8213-2cba23bfc6bc.png"/>
<img width="100%" src="https://user-images.githubusercontent.com/34959078/71590171-c1997500-2b27-11ea-8bef-fca9cab093ee.png"/>
</div>

7. >  please reduce a bit the padding between images

Done! ✅ 

We would need additional device testing on staging if that's possible, so merging to master and deploying a short time later would be useful or is the staging env capable of display the website with this branch?

**Comment by b-g** [comment]
@felixhaeberle Great!! 👍  Almost there ... just found tiny things:

**Comments**
- Sticky header style (buttom line) home looks slightly diff in comparison to subpages. On purpose?

- old bullet point 3
> Not sure. Do you want to stripe out the normal headings of the pages then and display the pages name in the heading then?

What about a "←" (back arrow) + "Subpage Title"? I would find it better to have the title of the subpage in the header instead of a pretty redundant OpenMoji all the time.

- Would change font weight of category to the one of "color" and "A-Z" (not bold)
![2020-01-05 at 12 42](https://user-images.githubusercontent.com/480224/71779712-0b1b1180-2fb9-11ea-9026-3b8377d78f33.jpg)

- Filter state "Date Added" gives ugly line break
![2020-01-05 at 12 44](https://user-images.githubusercontent.com/480224/71779717-2be36700-2fb9-11ea-9a53-1df5a57a0ebc.jpg)

- More padding after buttons SVG and PNG
![2020-01-05 at 12 46](https://user-images.githubusercontent.com/480224/71779783-b3c97100-2fb9-11ea-98fe-01a87c821d63.jpg)

**Staging**
 > We would need additional device testing on staging if that's possible, so merging to master and deploying a short time later would be useful or is the staging env capable of display the website with this branch?

I think I would simply merge it with master once the tiny issues above are done. You can also do it on your own (very busy next week). Don't want to hold you back. Just don't merge anything into production branch as this will deploy it. Your user should have the rights for it.

**Comment by felixhaeberle** [comment]
@b-g Thank you for the feedback and sorry for replying late! A lot projects 😄 
I'm going to implement your feedback in the next days. 💪

**Comment by b-g** [comment]
@felixhaeberle Great! Much looking forward!

**Comment by felixhaeberle** [comment]
@b-g 
Hey, sorry for being late 20 days 🙈! Busy doing projects at @hfg :)  

> Sticky header style (bottom line) home looks slightly diff in comparison to subpages. On purpose?

Yeah! Should this be changed? In case of the start page it seperates the emoji grid from the header which looks good in my opinion, on the other sites this is not needed because we're mostly going straight to text content or have a bit better "surrounding". 

> old bullet point 3
Not sure. Do you want to stripe out the normal headings of the pages then and display the pages name in the heading then?
What about a "←" (back arrow) + "Subpage Title"? I would find it better to have the title of the subpage in the header instead of a pretty redundant OpenMoji all the time.

This could be implemented, should we therefore take the pages name e.g. "Participate" or "Samples" for this? with a back arrow ? pointing to the start page? or the previous page (more complicated).

> Would change font weight of category to the one of "color" and "A-Z" (not bold)

Done ✅

> Filter state "Date Added" gives ugly line break

Done ✅ (for all devices down to 375px width, this is average)

> More padding after buttons SVG and PNG

Couldn't reproduce, which browser / OS is that? Can you look this up if it's a caching thing? :)

> Staging

Nice, I test it locally on my end! 👍 

#63

**Comment by felixhaeberle** [comment]
Could we postpone 
> old bullet point 3

to a new issue with a separate PR or commit ?
I would like to get this huge PR #63 done 😄

**Comment by b-g** [comment]
@felixhaeberle Yes. Will break move old bullet point into a new issue.
